export * from './lib/api-collection-combo-data-access.module'
export * from './lib/api-collection-combo.service'
export * from './lib/dto/admin-create-collection-combo.input'
export * from './lib/dto/admin-find-collection-combos.input'
export * from './lib/dto/admin-update-collection-combo.input'
export * from './lib/entity/collection-combo.entity'
